In [1]:
import os
import torch
import torchvision 
import torchvision.transforms as transforms

In [2]:
os.listdir('./monkey_images_dataset/training/training/')

['n0', 'n1', 'n2', 'n3', 'n4', 'n5', 'n6', 'n7', 'n8', 'n9']

In [3]:
train_path = './monkey_images_dataset/training/training/'

In [4]:
transformers = transforms.Compose([transforms.Resize((224,224)),
                                   transforms.ToTensor()
])

In [5]:
train_dataset = torchvision.datasets.ImageFolder(root=train_path, transform=transformers)

In [6]:
train_loader = torch.utils.data.DataLoader(dataset=train_dataset, batch_size=32, shuffle=False)

In [7]:
# With function calculate the mean & std for noramlization in transforms.Compose([]) function.
def get_mean_and_std(loader):
    mean = 0.
    std = 0.
    total_images_count = 0
    for images, _ in loader:
        image_count_in_batch = images.size(0)
        images = images.view(image_count_in_batch, images.size(1), -1)
        mean += images.mean(2).sum(0) 
        std += images.std(2).sum(0)
        total_images_count += image_count_in_batch
    mean /= total_images_count
    std/= total_images_count
    
    return mean, std
# call the function
get_mean_and_std(train_loader)

(tensor([0.4363, 0.4328, 0.3291]), tensor([0.2129, 0.2075, 0.2037]))

In [8]:
# Without declaring function calculate the mean & std for noramlization in transforms.Compose([]) function.
mean = 0.
std = 0.
nb_samples = 0.
for data, _ in train_loader:
    batch_samples = data.size(0)
    data = data.view(batch_samples, data.size(1), -1)
    mean += data.mean(2).sum(0)
    std += data.std(2).sum(0)
    nb_samples += batch_samples

mean /= nb_samples
std /= nb_samples

print(mean)
print(std)

tensor([0.4363, 0.4328, 0.3291])
tensor([0.2129, 0.2075, 0.2037])
